server:
  port: 0
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ech-10-168-142-108.mastercard.int:8761/eureka/,http://localhost:8761/eureka/
  instance:
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}    
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none  
    
